### ISSUE TITLE
how to specify the  data directory?

### ISSUE THREAD

**Issue by zacker0515** [tenet-org/tenet-mainnet#2]
I have changed ~/.tenetd/config/config.toml    
db_dir = "/data/tenet/tenet-mainnet/data"
but there was only about 7G files , and there are still 20G  files on ~/.tenetd/data/application.db 
how to change the application.db  save directory?

**Comment by wangchengao** [comment]
maybe you can use --home option in start args
```evmosd start  --home /data/tenet/tenet-mainnet```
